# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  workflow_call:
    inputs:
      registry:
        description: 'Login Registry'
        type: string
      reponame:
        description: 'the image name of the docker hub image'
        default: 'h2invent/jitsi-admin-matrix-bot-main'
        required: true
        type: string
      directory:
        description: 'the dir of the Dockerfile image'
        default: '.'
        required: true
        type: string
      dockerfile_path:
        description: 'the name of the Dockerfile image'
        default: './Dockerfile'
        required: true
        type: string
      version:
        description: 'the version/tag of the Dockerfile image'
        required: true
        type: string

    secrets:
      dockerhub_username:
        required: true
      dockerhub_password:
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get current Username
        id: date
        run: echo "${{ secrets.dockerhub_username }}"

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Write semantic Version in config file
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "<version-addhere>"
          replace: "${{ inputs.version }}"
          regex: false

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.reponame }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ inputs.directory }}
          file: ${{ inputs.dockerfile_path }}
          tags: ${{ inputs.version }}
